baseurl = "https://johannescopeland.com/"
title = "Johannes Copeland Hasche"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = false # Allow user HTML tags

[params]
    author = "Johannes Copeland Hasche"
    avatar = "avatar.jpg"
    # avatarDescription = "My avatar description"
    favicon = "favicon.ico"
    description = """
        Hello there!
        I'm a Business and Information System Engineering student in Germany.
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

# [[menu.main]]
#     identifier = "blog"
#     # name = "Blog" #If display text link, cancel comment out
#     pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
#     url = "/blog/"
#     weight = 10

[[menu.main]]
    identifier = "instagram"
    # name = "Twitter"
    pre = "<i class='fab fa-instagram fa-lg'></i>"
    url = "https://www.instagram.com/johanncopeland/"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/johanncopeland"
    weight = 30

[[menu.main]]
    identifier = "linkedin"
    # name = "LinkedIn"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/johannes-copelandhasche/"
    weight = 40

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:contact@johannescopeland.com"
    weight = 50
